<?php
/** @var \Winman\Bridge\Block\Invoices $block */

$id = $block->getRequest()->getParam('id');
$invoices = $block->getStatements($id);
?>
<?php if (isset($id)): ?>
    <?php if (is_array($invoices)): ?>
        <?php $invoice = $invoices[0]; ?>
        <div class="block">
            <div class="block-title">
                <span>
                    <?= __('Invoice') . ' - ' . $invoice->InvoiceId; ?>
                </span>
                <div class="primary wmn-view-all">
                    <a href="<?= $block->getUrl('customerportal/portal/invoices'); ?>"
                       class="action primary">
                        <span>
                            <?= __('View All Invoices'); ?>
                        </span>
                    </a>
                </div>
            </div>
            <div class="block-content">
                <div class="box">
                    <strong class="box-title"><span><?= __('Company Address'); ?></span></strong>
                    <p class="wmn-address">
                        <span>
                            <?= $invoice->BillingName; ?>
                        </span>
                        <span>
                            <?= str_replace('&#xD;&#xA;', '<br/>', $invoice->BillingAddress); ?>
                        </span>
                        <span>
                            <?= $invoice->BillingCity; ?>
                        </span>
                        <span>
                            <?= $invoice->BillingPostalCode; ?>
                        </span>
                        <span>
                            <?= $block->getCountryName($invoice->BillingCountryCode); ?>
                        </span>
                    </p>
                </div>
                <div class="box">
                    <strong class="box-title"><span><?= __('Shipping Address'); ?></span></strong>
                    <p class="wmn-address">
                        <span>
                            <?= $invoice->ShippingName; ?>
                        </span>
                        <span>
                            <?= str_replace('&#xD;&#xA;', '<br/>', $invoice->ShippingAddress); ?>
                        </span>
                        <span>
                            <?= $invoice->ShippingCity; ?>
                        </span>
                        <span>
                            <?= $invoice->ShippingPostalCode; ?>
                        </span>
                        <span>
                            <?= $block->getCountryName($invoice->ShippingCountryCode); ?>
                        </span>
                    </p>
                </div>
            </div>
        </div>
        <div class="block">
            <div class="block-content">
                <div class="box">
                    <strong class="box-title"><span><?= __('Invoice Details'); ?></span></strong>
                    <div class="box-content">
                        <div class="box wmn-box">
                            <div class="box-content">
                                <span>
                                    <?= __('Invoice ID') . ':&nbsp;'; ?>
                                </span>
                                <span>
                                    <?= __('Sales Order ID') . ':&nbsp;'; ?>
                                </span>
                                <span>
                                    <?= __('Invoice Date') . ':&nbsp;'; ?>
                                </span>
                                <span>
                                    <?= __('Invoice Due Date') . ':&nbsp;'; ?>
                                </span>
                                <span>
                                    <?= __('Status') . ':&nbsp;'; ?>
                                </span>
                            </div>
                        </div>
                        <div class="box wmn-box">
                            <div class="box-content">
                                <span>
                                    <?= $invoice->InvoiceId; ?>
                                </span>
                                <span>
                                    <?= $invoice->SalesOrderId; ?>
                                </span>
                                <span>
                                    <?= date('M d Y', strtotime($invoice->InvoiceDate)); ?>
                                </span>
                                <span>
                                    <?= date('M d Y', strtotime($invoice->InvoiceDueDate)); ?>
                                </span>
                                <span>
                                    <?= $invoice->InvoiceStatus; ?>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box">
                    <div class="box-content">
                        <div class="actions-toolbar">
                            <div class="primary wmn-print-order">
                                <a href="<?= $block->getUrl('customerportal/portal/overview') . '?pdf=salesinvoice&salesinvoiceid=' . $invoice->InvoiceId; ?>"
                                   class="action primary">
                                    <span>
                                        <?= __('Print Invoice'); ?>
                                    </span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="block">
            <div class="block-content">
                <strong class="box-title"><span><?= __('Invoice Items'); ?></span></strong>
                <div class="box-content">
                    <?php if (is_array($invoice->InvoiceItems)): ?>
                        <div class="table-wrapper">
                            <table class="data table wmn-table">
                                <thead>
                                <tr>
                                    <th class="col"><?= __('Item'); ?></th>
                                    <th class="col"><?= __('Description'); ?></th>
                                    <th class="col"><?= __('Quantity'); ?></th>
                                    <th class="col"><?= __('Unit Cost'); ?></th>
                                    <th class="col"><?= __('Line Cost'); ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php $invoice->InvoiceItems = $block->sortItems($invoice->InvoiceItems); ?>
                                <?php foreach ($invoice->InvoiceItems as $item): ?>
                                    <tr>
                                        <td class="col">
                                            <?php if (isset($item->FreightMethodId)): ?>
                                                <?= __('Shipping'); ?>
                                            <?php elseif (isset($item->FreeTextItem)): ?>
                                                <?= $item->FreeTextItem; ?>
                                            <?php elseif (isset($item->SundryId)): ?>
                                                <?= $item->SundryId; ?>
                                            <?php else: ?>
                                                <?= $item->Sku; ?>
                                            <?php endif; ?>
                                        </td>
                                        <td class="col">
                                            <?php if (isset($item->FreightMethodId)): ?>
                                                <?= __('Shipping') . '<br/>' . $item->Description; ?>
                                            <?php elseif (isset($item->FreeTextItem)): ?>
                                                <?= $item->FreeTextItem . '<br/>' . $item->Description; ?>
                                            <?php elseif (isset($item->SundryId)): ?>
                                                <?= $item->SundryId . '<br/>' . $item->Description; ?>
                                            <?php else: ?>
                                                <?= $item->Sku . '<br/>' . $item->ProductName; ?>
                                            <?php endif; ?>
                                        </td>
                                        <td class="col">
                                            <?= $item->Quantity; ?>
                                        </td>
                                        <td class="col">
                                            <?= $block->getCurrencySymbol($invoice->Currency) . number_format((float)$item->UnitPrice, 2, '.', ','); ?>
                                        </td>
                                        <td class="col">
                                            <?= $block->getCurrencySymbol($invoice->Currency) . number_format((float)($item->LineValue - $item->LineTaxValue), 2, '.', ','); ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    <?php else: ?>
                        <div class="message info">
                            <span>
                                <?= __('There are no items to display.'); ?>
                            </span>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="block">
            <div class="block-content">
                <div class="wmn-totals">
                    <div class="box wmn-box">
                        <div class="box-content">
                            <span>
                                <?= __('Subtotal') . ':&nbsp;'; ?>
                            </span>
                            <span>
                                <?= __('Tax') . ':&nbsp;'; ?>
                            </span>
                            <span>
                                <?= __('Invoice Total') . ':&nbsp;'; ?>
                            </span>
                            <span>
                                <?= __('Outstanding') . ':&nbsp;'; ?>
                            </span>
                        </div>
                    </div>
                    <div class="box wmn-box">
                        <div class="box-content">
                            <span>
                                <?= $block->getCurrencySymbol($invoice->Currency) . number_format((float)($invoice->InvoiceTotal - $invoice->TotalTaxValue), 2, '.', ','); ?>
                            </span>
                            <span>
                                <?= $block->getCurrencySymbol($invoice->Currency) . number_format((float)$invoice->TotalTaxValue, 2, '.', ','); ?>
                            </span>
                            <span>
                                <?= $block->getCurrencySymbol($invoice->Currency) . number_format((float)$invoice->TotalOrderValue, 2, '.', ','); ?>
                            </span>
                            <span>
                                <?= $block->getCurrencySymbol($invoice->Currency) . number_format((float)$invoice->OutstandingBalance, 2, '.', ','); ?>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php else: ?>
        <div class="block">
            <div class="block-title">
                <span>
                    <?= __('Invoice') . ' - ' . $id; ?>
                </span>
                <div class="primary wmn-view-all">
                    <a href="<?= $block->getUrl('customerportal/portal/invoices'); ?>"
                       class="action primary">
                        <span>
                            <?= __('View All Invoices'); ?>
                        </span>
                    </a>
                </div>
            </div>
            <div class="block-content">
                <div class="message info">
                    <span>
                        <?= __('Could not find invoice with ID') . '&nbsp;' . $id; ?>
                    </span>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="block">
        <div class="block-title"><span><?= __('Invoices'); ?></span></div>
        <div class="block-content">
            <?php if (is_array($invoices)): ?>
                <div class="table-wrapper orders-recent">
                    <table class="data table">
                        <thead>
                        <tr>
                            <th class="col"><?= __('Date'); ?></th>
                            <th class="col"><?= __('Type'); ?></th>
                            <th class="col"><?= __('Status'); ?></th>
                            <th class="col"><?= __('Invoice'); ?></th>
                            <th class="col"><?= __('Sales Order'); ?></th>
                            <th class="col"><?= __('Reference'); ?></th>
                            <th class="col"><?= __('Debit'); ?></th>
                            <th class="col"><?= __('Credit'); ?></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($invoices as $invoice): ?>
                            <tr>
                                <td class="col">
                                    <?= date('M d Y', strtotime($invoice->Date)); ?>
                                </td>
                                <td class="col">
                                    <?= $invoice->StatementLineType; ?>
                                </td>
                                <td class="col">
                                    <?= $invoice->Status; ?>
                                </td>
                                <td class="col">
                                    <a href="<?= $block->getUrl('customerportal/portal/invoices') . '?id=' . $invoice->InvoiceId; ?>">
                                        <?= $invoice->InvoiceId; ?>
                                    </a>
                                </td>
                                <td class="col">
                                    <a href="<?= $block->getUrl('customerportal/portal/orders') . '?id=' . $invoice->SalesOrderId; ?>">
                                        <?= $invoice->SalesOrderId; ?>
                                    </a>
                                </td>
                                <td class="col">
                                    <?= $invoice->CustomerOrderNumber; ?>
                                </td>
                                <td class="col">
                                    <?= $block->getCurrencySymbol($invoice->Currency) . number_format((float)$invoice->Debit, 2, '.', ','); ?>
                                </td>
                                <td class="col">
                                    <?= $block->getCurrencySymbol($invoice->Currency) . number_format((float)$invoice->Credit, 2, '.', ','); ?>
                                </td>
                                <td>
                                    <?php if ($invoice->StatementLineType === 'Invoice'): ?>
                                        <a href="<?= $block->getUrl('customerportal/portal/overview') . '?pdf=salesinvoice&salesinvoiceid=' . $invoice->InvoiceId; ?>"
                                           class="wmn-icon-link">
                                            <span class="wmn-icon wmn-print" aria-hidden="true"></span>
                                        </a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <div class="toolbar bottom">
                    <div class="pager">
                        <p class="toolbar-amount">
                            <span class="toolbar-number">
                                <?= __('Showing items %1 to %2 of %3 total', $block->getPageStart(), $block->getPageEnd(), $block->getTotalCount()); ?>
                            </span>
                        </p>
                        <?php if ($block->getTotalPages() > 1): ?>
                            <div class="pages">
                                <strong class="label pages-label" id="paging-label"><?= __('Page'); ?></strong>
                                <ul class="items pages-items" aria-labelledby="paging-label">
                                    <?php if ($block->getPage() > 1): ?>
                                        <li class="item pages-item-previous">
                                            <a class="action previous" href="<?= $block->getPreviousUrl(); ?>"
                                               title="<?= __('Previous'); ?>">
                                                <span class="label"><?= __('Page'); ?></span>
                                                <span><?= __('Previous'); ?></span>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($block->showJumpBack()): ?>
                                        <li class="item">
                                            <a class="page" href="<?= $block->getPageUrl(1); ?>">
                                                <span class="label"><?= __('Page'); ?></span>
                                                <span>1</span>
                                            </a>
                                        </li>
                                        <li class="item">
                                            <a class="page previous jump" href="<?= $block->getJumpBackUrl(); ?>">
                                                <span>...</span>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php foreach ($block->getVisiblePages() as $_page): ?>
                                        <?php if ($block->getPage() == $_page): ?>
                                            <li class="item current">
                                                <strong class="page">
                                                    <span class="label"><?= __('You\'re currently reading page'); ?></span>
                                                    <span><?= $_page; ?></span>
                                                </strong>
                                            </li>
                                        <?php else: ?>
                                            <li class="item">
                                                <a href="<?= $block->getPageUrl($_page); ?>" class="page">
                                                    <span class="label"><?= __('Page'); ?></span>
                                                    <span><?= $_page; ?></span>
                                                </a>
                                            </li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                    <?php if ($block->showJumpAhead()): ?>
                                        <li class="item">
                                            <a class="page next jump" href="<?= $block->getJumpAheadUrl(); ?>">
                                                <span>...</span>
                                            </a>
                                        </li>
                                        <li class="item">
                                            <a class="page" href="<?= $block->getPageUrl($block->getTotalPages()); ?>">
                                                <span class="label"><?= __('Page'); ?></span>
                                                <span><?= $block->getTotalPages(); ?></span>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($block->getPage() < $block->getTotalPages()): ?>
                                        <li class="item pages-item-next">
                                            <a class="action next" href="<?= $block->getNextUrl(); ?>"
                                               title="<?= __('Next'); ?>">
                                                <span class="label"><?= __('Page'); ?></span>
                                                <span><?= __('Next'); ?></span>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        <?php endif; ?>
                        <div class="limiter">
                            <strong class="limiter-label"><?= __('Show'); ?></strong>
                            <select id="limiter" class="limiter-options">
                                <option value="<?= $block->getSizeUrl(10); ?>"<?= $block->getSelectedStatus(10); ?>>
                                    10
                                </option>
                                <option value="<?= $block->getSizeUrl(20); ?>"<?= $block->getSelectedStatus(20); ?>>
                                    20
                                </option>
                                <option value="<?= $block->getSizeUrl(50); ?>"<?= $block->getSelectedStatus(50); ?>>
                                    50
                                </option>
                            </select>
                            <span class="limiter-text"><?= __('per page'); ?></span>
                        </div>
                    </div>
                </div>
            <?php else: ?>
                <div class="message info">
                    <span>
                        <?= __('There are no invoices to display.'); ?>
                    </span>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <script type="text/javascript">
      var elem = document.getElementById('limiter');

      elem.onchange = function () {
        window.location.href = elem.value;
      }
    </script>
<?php endif; ?>